spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/viavi
    username: root
    password: 122112
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
jwt:
  private-key: BaiEV+aB+DM7YqtOadi84CSEuQsHnlrb4/4qpkycEu4=
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
